---
development:
  cloud_name: dnk26i7hu
  api_key: '439324683695199'
  api_secret: hnpyI8VP3hQlIk0D7y6NJkbfsF8
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: dnk26i7hu
  api_key: '439324683695199'
  api_secret: hnpyI8VP3hQlIk0D7y6NJkbfsF8
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: dnk26i7hu
  api_key: '439324683695199'
  api_secret: hnpyI8VP3hQlIk0D7y6NJkbfsF8
  enhance_image_tag: true
  static_file_support: false
